name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
      with:
        # The Flutter version to make available on the path
        flutter-version: 1.20.0-8.0.pre.125 # optional
        # The Flutter build release channel
        channel: master # optional, default is stable
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
